# Basic info
title: Project SSG
description: My first SSG site - don't get too excited!
show-downloads: true
google analytics: 
baseurl: "" # Leer, wenn die Seite direkt unter meinname.github.io erreichbar ist
url: "https://surlyUser.github.io"

# Theme
# remote_theme: daattali/beautiful-jekyll
remote_theme: pages-themes/architect@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme

